version: "3.1"

services:
  api:
    build: .
    container_name: flask_api
    depends_on:
      - postgres
    ports:
      - 5001:5000
    networks:
      - postgres

  postgres:
    image: postgres
    container_name: flask_api_db
    # ports:
    #   - 5432:5432
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: flask
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
