version: "3.1"

services:
  api:
    build: .
    container_name: flask_api_test
    command: make run_test
    env_file:
      - ./.docker.env
    depends_on:
      - postgres
    ports:
      - 5001:5000
    networks:
      - postgres_test

  postgres:
    image: postgres
    container_name: flask_api_db_test
    # ports:
    #   - 5432:5432
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: flask-test
    networks:
      - postgres_test
    healthcheck:
      test: ping -c 2 flask_api_test || kill 1
      interval: 13s
      retries: 1
      start_period: 20s

networks:
  postgres_test:
    driver: bridge
